apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- secrets.yaml

images:
- name: python-db-app
  newName: airerik/python-db-app  # Замените на ваш Docker Hub username
  newTag: latest
