apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: test-app
type: Opaque
stringData:
  DB_HOST: "postgres.postgres.svc.cluster.local"  # Полное DNS-имя сервиса PostgreSQL в namespace postgres
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "admin"
  DB_PASSWORD: "postgres"  # Убедитесь, что это правильный пароль для пользователя admin
